# Generated by Django 3.0.2 on 2023-07-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('grades', models.FloatField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
