# Generated by Django 3.0.2 on 2023-08-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20230727_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_q',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('choice_a', models.CharField(max_length=255)),
                ('choice_b', models.CharField(max_length=255)),
                ('choice_c', models.CharField(max_length=255)),
                ('choice_d', models.CharField(max_length=255)),
                ('true_answer', models.CharField(max_length=255)),
                ('point', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Essay_q',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('point', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
